package wire_codes

// SERVER -> CLIENT
const (
	SERVER_INVALID uint32 = iota
	SERVER_PONG
	SERVER_ERROR
	SERVER_SWEEP
	SERVER_ANON_TOKEN_REFRESH
	SERVER_ANON_TOKEN_NEW
)

// CLIENT -> SERVER
const (
	CLIENT_INVALID uint32 = iota
	CLIENT_PING
	CLIENT_ERROR
	CLIENT_SWEEP
	CLIENT_ANON_TOKEN_REFRESH
	CLIENT_ANON_TOKEN_NEW
)
