package wire_codes

// SERVER -> CLIENT
const (
	SERVER_INVALID uint32 = iota
	SERVER_ERROR
	SERVER_SWEEP
	SERVER_ANON_TOKEN_REFRESH
	SERVER_ANON_TOKEN_NEW
	SERVER_ANON_TOKEN_LOGIN
	SERVER_SEND_ACTIVE_WORLDS
)

// CLIENT -> SERVER
const (
	CLIENT_INVALID uint32 = iota
	CLIENT_ERROR
	CLIENT_SWEEP
	CLIENT_ANON_TOKEN_REFRESH
	CLIENT_ANON_TOKEN_NEW
	CLIENT_ANON_TOKEN_LOGIN
	CLIENT_GET_ACTIVE_WORLDS
)

// SERVER ERROR CODES
const (
	ERR_S_INTERNAL_SERVER_ERROR uint32 = iota
	errMsgCount
)

var SERVER_ERROR_TEXT = [errMsgCount]string{
	ERR_S_INTERNAL_SERVER_ERROR: "internal server error: server log id %X",
}
