CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  email TEXT NOT NULL UNIQUE,
  hash_pass TEXT NOT NULL,
  use_name BOOLEAN DEFAULT FALSE NOT NULL,
  screen_name VARCHAR(12),
  playtime INTEGER DEFAULT 0 NOT NULL,
  score BIGINT DEFAULT 0 NOT NULL,
  score_sweeps BIGINT DEFAULT 0 NOT NULL,
  score_flags BIGINT DEFAULT 0 NOT NULL,
  sweeps INTEGER DEFAULT 0 NOT NULL,
  deaths INTEGER DEFAULT 0 NOT NULL,
  good_flags INTEGER DEFAULT 0 NOT NULL,
  warnings INTEGER DEFAULT 0 NOT NULL,
  banned BOOLEAN DEFAULT FALSE NOT NULL,
  ban_reason TEXT DEFAULT '(not banned)' NOT NULL,
  next_flag TIMESTAMP NOT NULL,
);

CREATE TABLE props (
    prop_id CHAR(8) PRIMARY KEY,
    val BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE tokens (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMP NOT NULL,
  revoked BOOLEAN DEFAULT FALSE NOT NULL,
  revoked_at TIMESTAMP NOT NULL
);

CREATE TABLE participation (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  world_id INTEGER NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  score BIGINT DEFAULT 0 NOT NULL,
  sweeps INTEGER DEFAULT 0 NOT NULL,
  good_flags INTEGER DEFAULT 0 NOT NULL,
  died BOOLEAN DEFAULT FALSE NOT NULL,
);

CREATE TABLE flags (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    world_id BIGINT NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
    pos INTEGER NOT NULL,
    good BOOLEAN NOT NULL,
);

CREATE TABLE worlds (
  id BIGSERIAL PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  cleared_at TIMESTAMP NOT NULL,
  expired BOOLEAN DEFAULT FALSE NOT NULL,
  cleared BOOLEAN DEFAULT FALSE NOT NULL,
  participants BIGINT DEFAULT 0 NOT NULL,
  total_score BIGINT DEFAULT 0 NOT NULL
  tile_state BYTEA
);